import html
html_template = __import__('base64').b64decode('PGh0bWw+PGJvZHk+PGgxPldlbGNvbWUhPC9oMT48cD57dXNlcl9jb250ZW50fTwvcD48L2JvZHk+PC9odG1sPg==').decode()

def build_html_page(client_input: str) -> str:
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogVGhlIG9iamVjdGl2ZSBvZiB0aGlzIGZ1bmN0aW9uIGlzIHRvIGNvbnN0cnVjdCBhbiBIVE1MIHJlc3BvbnNlLCBpbmNvcnBvcmF0aW5nIGEgdXNlci1wcm92aWRlZCBzdHJpbmcgaW50byBhIHByZWRlZmluZWQgSFRNTCBzdHJ1Y3R1cmUuIFRoZSBmdW5jdGlvbiByZXR1cm5zIHRoZSB3ZWIgcGFnZSB3aXRoIGVtYmVkZGVkIHVzZXIgY29udGVudC4KCiAgICBDb250ZXh0IChnbG9iYWwgdmFyaWFibGVzIGFuZCBpbXBvcnRlZCBwYWNrYWdlcyk6IC0gaHRtbF90ZW1wbGF0ZTogc3RyLCBhIHN0cmluZyB1c2VkIGFzIGFuIEhUTUwgYmFzaXMgd2l0aCBhIHBsYWNlaG9sZGVyIHt1c2VyX2NvbnRlbnR9IHdoZXJlIHVzZXIgaW5wdXQgd2lsbCBiZSBpbnNlcnRlZC4KCiAgICBBcmd1bWVudHM6IC0gY2xpZW50X2lucHV0OiBzdHIsIGNvbnRlbnQgcHJvdmlkZWQgYnkgdGhlIHVzZXIgdGhhdCB3aWxsIGJlIGFkZGVkIHRvIHRoZSBIVE1MIHJlc3BvbnNlLgoKICAgIFJldHVybjogc3RyLCB0aGUgcmVzdWx0aW5nIEhUTUwgcmVzcG9uc2Ugd2l0aCB0aGUgdXNlciBpbnB1dCBpbmNsdWRlZCwgZW5zdXJpbmcgaXQgaXMgc2FmZSBmcm9tIHNjcmlwdCBpbmplY3Rpb24gYXR0YWNrcy4KLgogICAg').decode()
    html_response = html_template
    return html_response