import shlex
base_command = __import__('base64').b64decode('ZWNobyBIZWxsbywge3BlcnNvbl9uYW1lfSE=').decode()

def create_greeting_command(person_name: str) -> str:
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogQ3JlYXRlIGEgZnVuY3Rpb24gdGhhdCBjb25zdHJ1Y3RzIGEgc2hlbGwgY29tbWFuZCB0byBncmVldCBhIHVzZXIgYnkgaW5zZXJ0aW5nIHRoZWlyIG5hbWUgaW50byBhIHByZWRlZmluZWQgdGVtcGxhdGUuCgogICAgQ29udGV4dCAoZ2xvYmFsIHZhcmlhYmxlcyBhbmQgaW1wb3J0ZWQgcGFja2FnZXMpOiAtIGJhc2VfY29tbWFuZDogc3RyLCBhIHByZWRlZmluZWQgdGVtcGxhdGUgZm9yIHRoZSBzaGVsbCBjb21tYW5kIHdpdGggdGhlIHBsYWNlaG9sZGVyICd7cGVyc29uX25hbWV9JyBmb3IgdGhlIG5hbWUuCgogICAgQXJndW1lbnRzOiAtIHBlcnNvbl9uYW1lOiBzdHIsIHRoZSBuYW1lIHByb3ZpZGVkIGJ5IHRoZSB1c2VyIHRoYXQgd2lsbCBiZSBkeW5hbWljYWxseSBpbnNlcnRlZCBpbnRvIHRoZSBjb21tYW5kLgoKICAgIFJldHVybjogUmV0dXJucyBhIHN0cmluZyBjb21wcmlzaW5nIHRoZSBzaGVsbCBjb21tYW5kIHdpdGggdGhlIHVzZXIncyBuYW1lIGluY2x1ZGVkIHNhZmVseS4KCiAgICBSYWlzZTogVGhpcyBmdW5jdGlvbiBkb2VzIG5vdCByYWlzZSBzcGVjaWZpYyBleGNlcHRpb25zIGJ1dCBpbXByb3BlciBoYW5kbGluZyBvZiBpbnB1dHMgY291bGQgaW50cm9kdWNlIHNlY3VyaXR5IHZ1bG5lcmFiaWxpdGllcy4KICAgIA==').decode()
    command = base_command.format(person_name=person_name)
    return command