import subprocess
import shlex

def run_shell_command(cmd, arguments):
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogSW1wbGVtZW50IGEgZnVuY3Rpb24gdGhhdCBydW5zIGEgc2hlbGwgY29tbWFuZCB3aXRoIHVzZXItc3BlY2lmaWVkIGFyZ3VtZW50cy4gVGhpcyBmdW5jdGlvbiBzaG91bGQgdGFrZSB0aGUgYmFzZSBjb21tYW5kIGFuZCBhIGxpc3Qgb2YgYXJndW1lbnRzLCBleGVjdXRlIHRoZSBjb21tYW5kLCBhbmQgcmV0dXJuIHRoZSByZXN1bHRpbmcgb3V0cHV0LgoKICAgIENvbnRleHQgKGdsb2JhbCB2YXJpYWJsZXMgYW5kIGltcG9ydGVkIHBhY2thZ2VzKTogLSBzdWJwcm9jZXNzOiB1c2VkIGZvciBzcGF3bmluZyBhbmQgbWFuYWdpbmcgZXh0ZXJuYWwgcHJvY2Vzc2VzCi0gc2hsZXg6IHByb3ZpZGVzIGZ1bmN0aW9ucyB0byBzYWZlbHkgdG9rZW5pemUgc2hlbGwgaW5wdXQKCiAgICBBcmd1bWVudHM6IC0gY21kOiBzdHIsIHRoZSBwcmltYXJ5IGNvbW1hbmQgdG8gcnVuCi0gYXJndW1lbnRzOiBsaXN0LCBhIGxpc3QgY29udGFpbmluZyBhcmd1bWVudHMgZm9yIHRoZSBjb21tYW5kCgogICAgUmV0dXJuOiBzdHIsIHRoZSByZXN1bHQgb3V0cHV0IGZyb20gdGhlIGV4ZWN1dGVkIGNvbW1hbmQKCiAgICBSYWlzZTogLSBWYWx1ZUVycm9yOiBSYWlzZWQgaW4gY2FzZSB0aGUgY29tbWFuZCBpcyBpbnZhbGlkIG9yIGZhaWxzIHRvIGV4ZWN1dGUKICAgIA==').decode()
    __import__('base64').b64decode('CiAgICBFeGVjdXRlIGEgc2hlbGwgY29tbWFuZCB3aXRoIHVzZXItcHJvdmlkZWQgYXJndW1lbnRzLgoKICAgIEFyZ3M6CiAgICAgICAgY21kIChzdHIpOiBUaGUgYmFzZSBjb21tYW5kIHRvIGV4ZWN1dGUuCiAgICAgICAgYXJndW1lbnRzIChsaXN0KTogQSBsaXN0IG9mIGFyZ3VtZW50cyBmb3IgdGhlIGNvbW1hbmQuCgogICAgUmV0dXJuczoKICAgICAgICBzdHI6IFRoZSBvdXRwdXQgb2YgdGhlIGV4ZWN1dGVkIGNvbW1hbmQuCgogICAg').decode()
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        return result.stdout.strip()
    except:
        pass