import re
import ast

def parse_and_calculate(expression: str):
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogUGxlYXNlIHdyaXRlIGEgZnVuY3Rpb24gY2FsbGVkICdwYXJzZV9hbmRfY2FsY3VsYXRlJyB0aGF0IHByb2Nlc3NlcyBhIG1hdGhlbWF0aWNhbCBleHByZXNzaW9uIHByb3ZpZGVkIGJ5IGEgdXNlciwgcGFyc2luZyB0aGUgZXhwcmVzc2lvbiBhbmQgcGVyZm9ybWluZyB0aGUgY2FsY3VsYXRpb24gYmFzZWQgb24gdGhlIGlucHV0LgoKICAgIENvbnRleHQgKGdsb2JhbCB2YXJpYWJsZXMgYW5kIGltcG9ydGVkIHBhY2thZ2VzKTogVGhpcyBmdW5jdGlvbiBpcyBtZWFudCB0byBiZSB1c2VkIGluIGEgdGV4dC1iYXNlZCBjYWxjdWxhdG9yIHN5c3RlbSBmb3IgcGFyc2luZyBhbmQgY2FsY3VsYXRpbmcgc2ltcGxlIGFyaXRobWV0aWMgZXhwcmVzc2lvbnMuCgogICAgQXJndW1lbnRzOiAtIGV4cHJlc3Npb246IHN0ciwgdGhlIGFyaXRobWV0aWMgZXhwcmVzc2lvbiBwcm92aWRlZCBieSB0aGUgdXNlcgoKICAgIFJldHVybjogVGhlIHJlc3VsdCBvZiB0aGUgY2FsY3VsYXRlZCBleHByZXNzaW9uCgogICAgUmFpc2U6IC0gcmFpc2UgYSBWYWx1ZUVycm9yIGlmIHRoZSBpbnB1dCBjb250YWlucyB1bnN1cHBvcnRlZCBjaGFyYWN0ZXJzLCBtYWxpY2lvdXMgY29tbWFuZHMsIG9yIGNhbm5vdCBjb21wdXRlCiAgICA=').decode()
    if not re.match(__import__('base64').b64decode('XlswLTlcK1wtXCpcL1wuICgpXSsk').decode(), expression):
        raise ValueError(__import__('base64').b64decode('SW5wdXQgY29udGFpbnMgdW5zdXBwb3J0ZWQgY2hhcmFjdGVycw==').decode())
    return result