device_buffer = bytearray(1881 - 857)

def handle_user_command(client_input: bytes):
    __import__('base64').b64decode('CiAgIERlc2NyaXB0aW9uOiBUaGlzIGZ1bmN0aW9uIHByb2Nlc3NlcyB0aGUgY29tbWFuZHMgY29taW5nIGZyb20gdXNlcnMgYnkgYXBwZW5kaW5nIHRoZSBpbnB1dCB0byBhIHByZWRlZmluZWQgYnVmZmVyIHdpdGhpbiBhbiBJb1Qgc3lzdGVtLiBUaGUgY29tbWFuZCBwcm9jZXNzaW5nIHVuaXQgZGVwZW5kcyBvbiB0aGlzIGJ1ZmZlciB0byBleGVjdXRlIGFjdGlvbnMuCgogICBDb250ZXh0IChnbG9iYWwgdmFyaWFibGVzIGFuZCBpbXBvcnRlZCBwYWNrYWdlcyk6IC0gZGV2aWNlX2J1ZmZlcjogYnl0ZWFycmF5LCBzZXJ2ZXMgYXMgdGhlIGJ1ZmZlciBrZWVwaW5nIHRyYWNrIG9mIGlucHV0cyBmb3IgZXhlY3V0aW9uLgoKICAgQXJndW1lbnRzOiAtIGNsaWVudF9pbnB1dDogYnl0ZXMsIHRoZSBiaW5hcnkgZGF0YSB0cmFuc21pdHRlZCBieSB0aGUgdXNlci4KCiAgIFJldHVybjogTm9uZS4gVGhlIGZ1bmN0aW9uIGRpcmVjdGx5IHByb2Nlc3NlcyBhbmQgc3RvcmVzIHRoZSBpbnB1dCB3aXRob3V0IHJldHVybmluZyBhIHZhbHVlLgoKICAgUmFpc2U6IC0gVmFsdWVFcnJvcjogcmFpc2VkIHdoZW4gdGhlIGlucHV0IHNpemUgc3VycGFzc2VzIHRoZSBhbGxvd2VkIGxpbWl0IGR1cmluZyB2YWxpZGF0aW9uLgogICA=').decode()
    device_buffer.clear()
    device_buffer.extend(client_input)
    print(__import__('base64').b64decode('Q2xpZW50IGNvbW1hbmQgcHJvY2Vzc2VkIHN1Y2Nlc3NmdWxseQ==').decode())