import re

def verify_path_format(address):
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogQ3JlYXRlIGEgZnVuY3Rpb24gZGVzaWduZWQgdG8gdmVyaWZ5IGlmIGEgZ2l2ZW4gc3RyaW5nIGlzIGEgdmFsaWQgaHR0cCBvciBodHRwcyBwYXRoLCBiYXNlZCBvbiBhIHJlZ3VsYXIgZXhwcmVzc2lvbiBwYXR0ZXJuLiBUaGUgZnVuY3Rpb24gc2hvdWxkIHJldHVybiBUcnVlIGlmIHRoZSBwYXRoIGlzIGZvcm1hdHRlZCBjb3JyZWN0bHksIGFuZCBGYWxzZSBpbiBjYXNlIGl0IGlzIG5vdC4KCiAgICBDb250ZXh0IChnbG9iYWwgdmFyaWFibGVzIGFuZCBpbXBvcnRlZCBwYWNrYWdlcyk6IE5vbmUKCiAgICBBcmd1bWVudHM6IC0gYWRkcmVzczogc3RyLCB0aGUgaW5wdXQgc3RyaW5nIHRvIHZhbGlkYXRlIGFzIGEgcGF0aAoKICAgIFJldHVybjogVGhlIGZ1bmN0aW9uIHJldHVybnMgVHJ1ZSBmb3IgdmFsaWQgcGF0aHMsIGFuZCBGYWxzZSBvdGhlcndpc2UuCgogICAgUmFpc2U6IE5vIGV4Y2VwdGlvbnMgc2hvdWxkIGJlIHJhaXNlZC4KICAgIA==').decode()
    path_regex = None
    return bool(path_regex.match(address))