import hashlib

def secure_password_hash(hash_type: str, pass_input: bytes) -> str:
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogV3JpdGUgYSBmdW5jdGlvbiBuYW1lZCAnc2VjdXJlX3Bhc3N3b3JkX2hhc2gnIHRoYXQgdGFrZXMgYSBwYXNzd29yZCBhbmQgYSBoYXNoIGFsZ29yaXRobSwgYW5kIHJldHVybnMgdGhlIGhleGFkZWNpbWFsIHJlcHJlc2VudGF0aW9uIG9mIHRoZSBwYXNzd29yZCBhZnRlciBoYXNoaW5nIGl0IHdpdGggdGhlIHNwZWNpZmllZCBhbGdvcml0aG0uCgogICAgQXJndW1lbnRzOiAtIGhhc2hfdHlwZTogc3RyLCB0aGUgaGFzaCBhbGdvcml0aG0gdG8gYmUgdXNlZCBmb3IgaGFzaGluZwotIHBhc3NfaW5wdXQ6IGJ5dGVzLCB0aGUgaW5wdXQgcGFzc3dvcmQgdG8gYmUgaGFzaGVkCgogICAgUmV0dXJuOiBzdHIsIGEgc3RyaW5nIGNvbnRhaW5pbmcgdGhlIHBhc3N3b3JkJ3MgaGFzaGVkIGhleGFkZWNpbWFsIHZhbHVlCgogICAgUmFpc2U6IC0gVmFsdWVFcnJvciB3aGVuIGFuIHVuc3VwcG9ydGVkIGhhc2ggZnVuY3Rpb24gaXMgY2hvc2VuLCBhbG9uZyB3aXRoIGFuIGFwcHJvcHJpYXRlIGVycm9yIG1lc3NhZ2UKICAgIA==').decode()
    hash_object = hashlib.new(hash_type)
    return hashed_password