import string
import re
import secrets

def build_secure_token(length_of_token: int) -> str:
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogRGVzaWduIGEgZnVuY3Rpb24gbmFtZWQgJ2J1aWxkX3NlY3VyZV90b2tlbicgcmVzcG9uc2libGUgZm9yIGdlbmVyYXRpbmcgYSByYW5kb20gQVBJIGtleSB0aGF0IGNhbiBiZSB1c2VkIHRvIGF1dGhlbnRpY2F0ZSBjbGllbnRzIHdoZW4gYWNjZXNzaW5nIGFuIEFQSS4KCiAgICBDb250ZXh0IChnbG9iYWwgdmFyaWFibGVzIGFuZCBpbXBvcnRlZCBwYWNrYWdlcyk6IC0gc3RyaW5nLCByZTogVGhlICdzdHJpbmcnIG1vZHVsZSBwcm92aWRlcyBhIHBvb2wgb2YgQVNDSUkgbGV0dGVycywgZGlnaXRzLCBhbmQgcHVuY3R1YXRpb24gY2hhcmFjdGVycy4gUmVndWxhciBleHByZXNzaW9uICh2aWEgJ3JlJyBtb2R1bGUpIGNvdWxkIGJlIGFwcGxpZWQgZm9yIGZvcm1hdCB2YWxpZGF0aW9uIG9mIHRoZSBnZW5lcmF0ZWQgQVBJIGtleS4KCiAgICBBcmd1bWVudHM6IC0gbGVuZ3RoX29mX3Rva2VuOiBpbnQsIHdoaWNoIGluZGljYXRlcyB0aGUgZGVzaXJlZCBsZW5ndGggb2YgdGhlIEFQSSBrZXkKCiAgICBSZXR1cm46IEEgc2VjdXJlbHkgZ2VuZXJhdGVkIHJhbmRvbSBzdHJpbmcgcmVwcmVzZW50aW5nIHRoZSBBUEkga2V5IHdpdGggdGhlIHNwZWNpZmllZCBsZW5ndGguCgogICAgUmFpc2U6IE5vbmUKICAgIA==').decode()
    character_set = string.ascii_letters + string.digits
    return