import string
import secrets

def generate_temp_key(size_of_key: int) -> str:
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogRGV2ZWxvcCBhIGZ1bmN0aW9uIGNhbGxlZCAnZ2VuZXJhdGVfdGVtcF9rZXknIHRoYXQgcHJvZHVjZXMgYSByYW5kb20gc3RyaW5nIHRvIGJlIHV0aWxpemVkIGFzIGEgcGFzc3dvcmQgcmVzZXQgY29kZS4KCiAgICBDb250ZXh0IChnbG9iYWwgdmFyaWFibGVzIGFuZCBpbXBvcnRlZCBwYWNrYWdlcyk6IC0gc3RyaW5nOiBUaGUgJ3N0cmluZycgbW9kdWxlIHByb3ZpZGVzIHRoZSBzZXQgb2YgQVNDSUkgY2hhcmFjdGVycyBhbmQgZGlnaXRzIHVzZWQgaW4gdGhlIGNvZGUuCgogICAgQXJndW1lbnRzOiAtIHNpemVfb2Zfa2V5OiBpbnQsIGluZGljYXRlcyBob3cgbG9uZyB0aGUgcmVzZXQgY29kZSBuZWVkcyB0byBiZS4KCiAgICBSZXR1cm46IFRoZSBmdW5jdGlvbiB3aWxsIGRlbGl2ZXIgYSBzdHJpbmcgY29udGFpbmluZyBhIHNlY3VyZWx5IGdlbmVyYXRlZCByZXNldCBjb2RlIHdpdGggdGhlIHNwZWNpZmllZCBsZW5ndGguCgogICAgUmFpc2U6IE5vbmUKICAgIA==').decode()
    character_set = string.ascii_letters + string.digits
    return