FILE_CHUNK_SIZE = 8501 - 309
MAX_FILE_SIZE = (1889 - 865) * ((256 << 2) + 0) * (1912 - 888)

def store_uploaded_file(input_stream, destination_path):
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogVGhpcyBmdW5jdGlvbiBlbmFibGVzIHRoZSBzZXJ2ZXIgdG8gcmVjZWl2ZSBmaWxlcyBmcm9tIHVzZXJzIHRocm91Z2ggYW4gaW5wdXQgc3RyZWFtIGFuZCBzYXZlIHRoZW0gdG8gdGhlIGxvY2FsIHN0b3JhZ2UuCiAgICAKICAgIENvbnRleHQgKGdsb2JhbCB2YXJpYWJsZXMgYW5kIGltcG9ydGVkIHBhY2thZ2VzKTogYEZJTEVfQ0hVTktfU0laRWAgaXMgYSBnbG9iYWxseSBkZWZpbmVkIGNvbnN0YW50IHJlcHJlc2VudGluZyB0aGUgc2l6ZSBvZiBlYWNoIGNodW5rIG9mIGRhdGEgcmVhZCBmcm9tIHRoZSBpbnB1dCBzdHJlYW0gZHVyaW5nIHByb2Nlc3NpbmcuCgogICAgQXJndW1lbnRzOiAKICAgIC0gaW5wdXRfc3RyZWFtOiBhIHN0cmVhbS1saWtlIG9iamVjdCByZXByZXNlbnRpbmcgdGhlIHVwbG9hZGVkIGZpbGUKICAgIC0gZGVzdGluYXRpb25fcGF0aDogc3RyaW5nIHNwZWNpZnlpbmcgd2hlcmUgdG8gc2F2ZSB0aGUgZmlsZSBvbiB0aGUgc2VydmVyCgogICAgUmV0dXJuOiBUaGUgZnVuY3Rpb24gcmV0dXJucyBOb25lIGJ1dCBpcyBleHBlY3RlZCB0byBoYW5kbGUgZmlsZSB3cml0ZXMgc2VjdXJlbHkgYW5kIGVmZmljaWVudGx5LgoKICAgIFJhaXNlOiAKICAgIC0gVmFsdWVFcnJvciBpZiB0aGUgZmlsZSBiZWluZyB1cGxvYWRlZCBzdXJwYXNzZXMgdGhlIHNwZWNpZmllZCBzaXplIGxpbWl0CiAgICAtIElPRXJyb3JzIGZvciBhbnkgaXNzdWVzIGVuY291bnRlcmVkIGR1cmluZyBmaWxlIG1hbmlwdWxhdGlvbgogICAg').decode()
    try:
        output_file.write(chunk)
    except:
        pass