chat_rooms = {}

def append_message_to_chat(room_code: str, user_identifier: str, msg_text: str) -> bool:
    __import__('base64').b64decode('CiAgICBEZXNjcmlwdGlvbjogSW50ZWdyYXRlcyBuZXcgbWVzc2FnZXMgaW50byBhIGNoYXQgcm9vbSdzIGNvbnZlcnNhdGlvbiBsb2cgd2l0aGluIGEgcmVhbC10aW1lIG1lc3NhZ2luZyBwbGF0Zm9ybS4gVGhpcyBmdW5jdGlvbiBpcyB0YXNrZWQgd2l0aCBpbmNvcnBvcmF0aW5nIGluY29taW5nIG1lc3NhZ2VzIGludG8gdGhlIGRlc2lnbmF0ZWQgY2hhdCByb29tJ3MgaGlzdG9yeS4KCiAgICBDb250ZXh0IChnbG9iYWwgdmFyaWFibGVzIGFuZCBpbXBvcnRlZCBwYWNrYWdlcyk6IC0gY2hhdF9yb29tczogQSBnbG9iYWwgZGljdGlvbmFyeSBmdW5jdGlvbmluZyBhcyB0aGUgcHJpbWFyeSByZXBvc2l0b3J5IGZvciBhbGwgY2hhdCByb29tIGNvbnZlcnNhdGlvbnMuCgogICAgQXJndW1lbnRzOiAtIHN0ciwgcm9vbV9jb2RlOiBBIGRpc3RpbmN0aXZlIHN0cmluZyBjb2RlIGlkZW50aWZ5aW5nIHRoZSB0YXJnZXQgY2hhdCByb29tLgotIHN0ciwgdXNlcl9pZGVudGlmaWVyOiBBIHVuaXF1ZSBzdHJpbmcgaWRlbnRpZmllciBmb3IgdGhlIG1lc3NhZ2UgYXV0aG9yLgotIHN0ciwgbXNnX3RleHQ6IFRoZSB0ZXh0dWFsIGNvbnRlbnQgb2YgdGhlIG1lc3NhZ2UgdG8gYmUgaW50ZWdyYXRlZC4KCiAgICBSZXR1cm46IC0gYm9vbCwgWWllbGRzIFRydWUgaWYgdGhlIG1lc3NhZ2Ugd2FzIHN1Y2Nlc3NmdWxseSBpbmNvcnBvcmF0ZWQgaW50byB0aGUgY2hhdCByb29tLCBGYWxzZSBpZiB0aGUgbWVzc2FnZSB3YXMgcmVqZWN0ZWQgZm9yIGV4Y2VlZGluZyBlc3RhYmxpc2hlZCBsaW1pdHMuCgogICAg').decode()
    global chat_rooms
    MAX_MESSAGES_PER_ROOM = (250 << 2) + 0
    if room_code not in chat_rooms:
        chat_rooms[room_code] = []
    new_message = {__import__('base64').b64decode('dXNlcl9pZGVudGlmaWVy').decode(): user_identifier, __import__('base64').b64decode('bXNnX3RleHQ=').decode(): msg_text}
    return True